
# Rotas Usuario

POST http://127.0.0.1:8000/api/cadastro/ HTTP/1.1
content-type: application/json

{
    "username": "Eduassrdaao",
    "password": "1234",
    "email":"Eduardosas@gmail.com",
    "cargo": "Aluno",
    "cpf":"12245545",
    "numero": "3215145"
}

###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "Eduassrdaao",
    "password": "1234"
}


###
POST  http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token e766bb5443a7249d6c2376c27d2cc33fc459cd39




###

POST http://127.0.0.1:8000/api/perfil_cadastro/
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1

{
    "idade":25,
    "peso":75,
    "altura":174,
    "cep":"45415",
    "numero":325

}
###


GET http://127.0.0.1:8000/api/perfil_usuario/
Content-Type: application/json
Authorization: Token e766bb5443a7249d6c2376c27d2cc33fc459cd39

###



POST http://127.0.0.1:8000/api/fazer_checkin/
Content-Type: application/json
Authorization: Token c9d0153d5ea80732adcafb87954164f1adcba25f

###



# Rotas Planos Associados

POST http://127.0.0.1:8000/api/cadastrar_plano/
Content-Type: application/json
Authorization: Token b594181a58feaa1d7a989d1214fdd3aa2dac613a

{
    "nome":"Plano 1",
    "descricao":"Plano 1 premium",
    "valor":1220

}
###
           
