
# Rotas Usuario

# Cadastrar aluno
POST http://127.0.0.1:8000/api/cadastro/ HTTP/1.1
content-type: application/json

{
    "username": "Eduassrdaao",
    "password": "1234",
    "email":"Eduardosas@gmail.com",
    "cargo": "Aluno",
    "cpf":"12245545",
    "numero": "3215145"
}

###

# Fazer login no sistema
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "Eduassrdaao",
    "password": "1234"
}


###

# Cadastrar Fazer logout
POST  http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token e766bb5443a7249d6c2376c27d2cc33fc459cd39


###

#Cadastrar Perfil relacionado a o usuario logado
POST http://127.0.0.1:8000/api/perfil_cadastro/
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1

{
    "idade":25,
    "peso":75,
    "altura":174,
    "cep":"45415",
    "numero":325

}
###

#Obter informaçoes do perfil do usuario logado
GET http://127.0.0.1:8000/api/perfil_usuario/
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1


###

# Editar informaçoes do perfil
PUT http://127.0.0.1:8000/api/editar_perfil/
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1
{
  "Usuario": {
    "id": 6,
    "username": "Eduassrdaao",
    "cargo": "Aluno",
    "email": "Eduardosas@gmail.com",
    "password": "pbkdf2_sha256$720000$CX67m6p2g4xS6ER4WnwCyg$SQfZfGW1WJRkwSscIb2EWKqefEPlh+qBI8w1uhm99fg=",
    "cpf": "12245545",
    "telefone": null
  },
  "perfil": {
    "id": 5,
    "idade": 25,
    "peso": 75,
    "altura": "174.00",
    "cep": 45415,
    "numero": 325,
    "usuario": 6
  }
}
###


# Fazer checking em uma academia
POST http://127.0.0.1:8000/api/fazer_checkin/
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1

###

# Fazer cadastro em um plano de associação passando o id do plano na rota
POST http://127.0.0.1:8000/api/cadastrar_aluno_plano/2
Content-Type: application/json
Authorization: Token c95c8f751b244c3b222ac9bb2b3356bfe100c0d1

###

# Rotas Planos Associados

# Cadastro de plano pelo gerente (só o gerente pode cadastrar)
POST http://127.0.0.1:8000/api/cadastrar_plano/
Content-Type: application/json
Authorization: Token b594181a58feaa1d7a989d1214fdd3aa2dac613a

{
    "nome":"Plano 1",
    "descricao":"Plano 1 premium",
    "valor":1220

}
###

#Listar todos os planos existentes no banco de dados
GET http://127.0.0.1:8000/api/listar_planos/
Content-Type: application/json
Authorization: Token b594181a58feaa1d7a989d1214fdd3aa2dac613a

###

# Listar informaçoes de um plano especifico passando o id na rota
GET http://127.0.0.1:8000/api/listar_planos_id/1
Content-Type: application/json
Authorization: Token b594181a58feaa1d7a989d1214fdd3aa2dac613a

###


          