
# Rotas Usuario

POST http://127.0.0.1:8000/api/cadastro/ HTTP/1.1
content-type: application/json

{
    "username": "jonass",
    "password": "1234",
    "email":"jonas@gmail.com",
    "cargo": "Aluno",
    "cpf":"12245545",
    "numero": 15
}

###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "username": "jonass",
    "password": "1234"
}


###
POST  http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Token 9bbeb24ddb88b1be8f21ba5cd5e6d1447eccac6a




###

POST http://127.0.0.1:8000/api/perfil_cadastro/
Content-Type: application/json
Authorization: Token 9bbeb24ddb88b1be8f21ba5cd5e6d1447eccac6a

{
    "idade":25,
    "peso":75,
    "altura":174,
    "cep":"45415",
    "numero":325

}
###


GET http://127.0.0.1:8000/api/perfil_usuario/
Content-Type: application/json
Authorization: Token 9bbeb24ddb88b1be8f21ba5cd5e6d1447eccac6a

###


# Rotas Planos Associados

POST http://127.0.0.1:8000/api/cadastrar_plano/
Content-Type: application/json
Authorization: Token b594181a58feaa1d7a989d1214fdd3aa2dac613a

{
    "nome":"Plano 1",
    "descricao":"Plano 1 premium",
    "valor":1220

}
###
           
