# Generated by Django 4.2.9 on 2024-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('A', 'aluno'), ('G', 'Gerente'), ('F', 'funcionario')], default='A', max_length=1),
        ),
    ]
