# Generated by Django 4.2.9 on 2024-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymgo', '0002_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('A', 'aluno'), ('G', 'Gerente'), ('F', 'funcionario')], max_length=1),
        ),
    ]
