# Generated by Django 5.0.1 on 2024-01-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymgo', '0004_usuario_cpf_usuario_telefone_alter_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano_associacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='plano',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymgo.plano_associacao'),
        ),
    ]
