# Generated by Django 5.0.1 on 2024-01-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymgo', '0005_remove_plano_associacao_usuario_perfil_plano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plano_associacao',
            new_name='PlanoAssociacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='plano',
        ),
        migrations.AddField(
            model_name='usuario',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymgo.planoassociacao'),
        ),
    ]
