# Generated by Django 5.0.1 on 2024-01-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymgo', '0006_rename_plano_associacao_planoassociacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planoassociacao',
            old_name='descriçao',
            new_name='descricao',
        ),
    ]
